name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set Version
      run: echo "VERSION=1.$(date +%j).${{ github.run_number }}" >> $GITHUB_ENV
    - name: Echo Version
      run: echo "VERSION=$VERSION"
    - uses: actions/setup-dotnet@v2
      env:
        NUGET_AUTH_TOKEN: ${{github.token}}
      with:
        dotnet-version: 6.0.x
        source-url: https://nuget.pkg.github.com/yadayadasoftware/index.json
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish NuGet
      run: dotnet pack --no-build --include-source
    - name: Publish Package To GitHub
      run: |
        cat /home/runner/work/utilities/utilities/nuget.config
        dotnet nuget push **/*.nupkg --source "https://nuget.pkg.github.com/yadayadasoftware/index.json"
